GAME_PADDLE_SPEED_EFFECT_ON_BALL_VELOCITY = 0.5
GAME_MAX_BALL_VERTICAL_SPEED_PROPORTION = 1.5   # 0 = only horizontal,  1 = 45 degrees, infinity = 90 degrees
GAME_BALL_HOLD_TIME = 1
GAME_BALL_START_SPEED = 6
GAME_BALL_SPEED_INCREASE_RATE = .2
GAME_BALL_BOUNCE_VELOCITY_RANDOMNESS_PROPORTION = 0.1
GAME_BALL_VELOCITY_RANDOMNESS_MINIMUM = 0.1
GAME_START_FULLSCREEN = False
GAME_ANTIALIASING = True

GAME_PADDLE_SIZES = [(0.3, 1), (0.25, 1.5), (0.75, 2.5)]
GAME_BALL_SIZES = [0.2, 0.5, 1]

JUICE_SCREEN_MOVEMENT_FROM_PADDLE_LERP_SPEED = 8
JUICE_SCREEN_MOVEMENT_FROM_PADDLE_MAX_VERTICAL = 0.3
JUICE_SCREEN_MOVEMENT_FROM_PADDLE_MAX_ROTATION_DEGREES = 4

JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_RETURN_LERP_SPEED = 8
JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_MIN_X = .1
JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_MAX_X = 10
JUICE_SCREEN_MOVEMENT_FROM_BALL_SPEED_FOR_KNOCK_MAX_X = 20
JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_MIN_Y = .1
JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_MAX_Y = 5
JUICE_SCREEN_MOVEMENT_FROM_BALL_SPEED_FOR_KNOCK_MAX_Y = 10

JUICE_PADDLE_KNOCKBACK = 0.5
JUICE_PADDLE_KNOCKBACK_RETURN_LERP_SPEED = 4
