GAME_PADDLE_SPEED_EFFECT_ON_BALL_VELOCITY = 0.25
GAME_PADDLE_SPEED_EFFECT_ON_BALL_SPIN = 0.2
GAME_MAX_BALL_VERTICAL_SPEED_PROPORTION = 1.5   # 0 = only horizontal,  1 = 45 degrees, infinity = 90 degrees
GAME_BALL_HOLD_TIME = 1
GAME_BALL_START_SPEED = 2
GAME_BALL_SPEED_INCREASE_RATE = 0.1
GAME_SPIN_ENABLED = False
GAME_BALL_SPIN_EFFECT_ON_BALL_VELOCITY = 0.5
GAME_BALL_SPIN_SPEED_VISUAL_MULTIPIER = 16
GAME_BALL_BOUNCE_VELOCITY_RANDOMNESS_PROPORTION = 0.1
GAME_BALL_VELOCITY_RANDOMNESS_MINIMUM = 0.5

JUICE_SCREEN_MOVEMENT_FROM_PADDLE_LERP_SPEED = 8
JUICE_SCREEN_MOVEMENT_FROM_PADDLE_MAX_VERTICAL = 0.3
JUICE_SCREEN_MOVEMENT_FROM_PADDLE_MAX_ROTATION_DEGREES = 2

JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK_RETURN_LERP_SPEED = 4
JUICE_SCREEN_MOVEMENT_FROM_BALL_KNOCK = 0.5

JUICE_PADDLE_KNOCKBACK = 0.5
JUICE_PADDLE_KNOCKBACK_RETURN_LERP_SPEED = 4
